org: boxysean
service: kenken-gg-api

frameworkVersion: ">=1.50.0"

provider:
  name: aws
  runtime: java8
  cfnRole: "arn:aws:iam::858316752957:role/serverless-deployment"

stage: prod
region: us-east-1

# plugins:
#   - serverless-domain-manager

package:
  artifact: target/scala-2.13/solvemykenken-assembly-1.0.jar

functions:
  solve:
    handler: com.solvemykenken.aws.ApiGatewayHandler
    events:
    - http:
        path: solve
        method: post

#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
#    events:
#      - http:
#          path: users/create
#          method: get
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#      - alexaSkill: amzn1.ask.skill.xx-xx-xx-xx
#      - alexaSmartHome: amzn1.ask.skill.xx-xx-xx-xx
#      - iot:
#          sql: "SELECT * FROM 'some_topic'"
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.ec2"
#            detail-type:
#              - "EC2 Instance State-change Notification"
#            detail:
#              state:
#                - pending
#      - cloudwatchLog: '/aws/lambda/hello'
#      - cognitoUserPool:
#          pool: MyUserPool
#          trigger: PreSignUp

#    Define function environment variables here
#    environment:
#      variable2: value2

custom:
  customDomain:
    domainName: api.kenken.gg
    stage: ci
    certificateArn: arn:aws:acm:us-east-1:858316752957:certificate/f90395ab-7430-4eb1-a847-3cc312bfd23d
    createRoute53Record: true
    hostedZoneId: Z2E3YTMST0TS6T

# # you can add CloudFormation resource templates here
# resources:
#   Resources:
#     ApiDns:
#       Type: AWS::Route53::RecordSetGroup
#       Properties:
#         HostedZoneName: kenken.gg
#         RecordSets:
#         - Name: api.kenken.gg
#           Type: A
#           AliasTarget:
#             HostedZoneId: !Join ['ID:', [!Ref 'HostedZoneId']]
#             # DNSName: !GetAtt [WebsiteCloudFront, DomainName]
#             DNSName: "myfakedomain.kenken.gg"
#   Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
