name: API
on:
  push:
    paths:
      - 'api/*'
      - .github/workflows/api.yaml

jobs:
  test:
    name: Test API
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Test
      working-directory: api
      run: make test

  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Deploy
      working-directory: api
      env:
        AWS_ACCESS_KEY_ID: AKIA4PV5KJA6T26A6M5U
        AWS_SECRET_ACCESS_KEY: AWS_SECRET_KEY_GITHUB_ACTIONS
      run: make deploy
