name: Web
on:
  push:
    paths:
      - 'web/*'

jobs:
  test:

    name: Test Web
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Test
      working-directory: web
      run: make test
