name: Web
on:
  push:
    paths:
      - 'web/*'
      - .github/workflows/web.yaml

jobs:
  test:

    name: Test Web
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Test
      working-directory: web
      env:
        CI: true
      run: make test

  deploy:
    name: Deploy Web
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Deploy
      working-directory: web
      env:
        CI: true
        AWS_ACCESS_KEY_ID: AKIA4PV5KJA6T26A6M5U
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_GITHUB_ACTIONS }}
      run: make deploy
