name: Web
on: [push]

jobs:
  test:

    name: Test Web
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: npm install, build, and test
      working-directory: web
      env:
        CI: true
      run: |
        npm install
        npm run build
        npm test
